
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           52738
     no. of nonzeroes in lower triangle of a =         2377532
     no. of nonzeroes in the factor l        =        16273190
     ratio of nonzeroes in factor (min/max)  =          0.8773
     number of super nodes                   =            1954
     maximum order of a front matrix         =            1113
     maximum size of a front matrix          =          619941
     maximum size of a front trapezoid       =          338316
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      8.0167D+09
     no. of floating point ops for solve     =      6.1402D+07
     ratio of flops for factor (min/max)     =          0.9021
     ratio of allocated memory (max/min)     =          1.1530
     number of positive pivots               =           52738
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.012000
     time (cpu & wall) for ordering          =        0.140625        0.141000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.093750        0.100000
     time (cpu & wall) for numeric factor    =        0.250000        0.247000
     computational rate (gflops) for factor  =       32.066676       32.456150
     time (cpu & wall) for numeric solve     =        0.015625        0.015000
     computational rate (gflops) for solve   =        3.929710        4.093447
     effective I/O rate (GB/sec) for solve   =       14.640471       15.250491

     no input or output performed

  Solver Memory allocated on core    0       =       56.183 MB
  Solver Memory allocated on core    1       =       52.430 MB
  Solver Memory allocated on core    2       =       60.451 MB
  Solver Memory allocated on core    3       =       56.781 MB
  Total Solver Memory allocated by all cores =      225.845 MB

