
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           52738
     no. of nonzeroes in lower triangle of a =         4385314
     no. of nonzeroes in the factor l        =        20408350
     ratio of nonzeroes in factor (min/max)  =          0.8909
     number of super nodes                   =            1665
     maximum order of a front matrix         =            1314
     maximum size of a front matrix          =          863955
     maximum size of a front trapezoid       =          733650
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.2437D+10
     no. of floating point ops for solve     =      7.8005D+07
     ratio of flops for factor (min/max)     =          0.9170
     ratio of allocated memory (max/min)     =          1.1982
     number of positive pivots               =           52738
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.046875        0.042822
     time (cpu & wall) for ordering          =        0.062500        0.070980
     time (cpu & wall) for other matrix prep =        0.015625        0.014292
     time (cpu & wall) for value input       =        0.046875        0.035924
     time (cpu & wall) for matrix distrib.   =        0.187500        0.196473
     time (cpu & wall) for numeric factor    =        0.375000        0.384303
     computational rate (gflops) for factor  =       33.165294       32.362464
     time (cpu & wall) for numeric solve     =        0.015625        0.015535
     computational rate (gflops) for solve   =        4.992327        5.021153
     effective I/O rate (GB/sec) for solve   =       18.599344       18.706736

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        102357.        1. MB
                95-   1        131072.        1. MB        103421.        1. MB
                95-   2        131072.        1. MB        101847.        1. MB
                95-   3        131072.        1. MB        105228.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        412853.        3. MB


  Solver Memory allocated on core    0       =       94.646 MB
  Solver Memory allocated on core    1       =       84.203 MB
  Solver Memory allocated on core    2       =       91.451 MB
  Solver Memory allocated on core    3       =      100.891 MB
  Total Solver Memory allocated by all cores =      371.191 MB

