
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           53106
     no. of nonzeroes in lower triangle of a =         2390590
     no. of nonzeroes in the factor l        =        16052976
     ratio of nonzeroes in factor (min/max)  =          0.8673
     number of super nodes                   =            2007
     maximum order of a front matrix         =            1143
     maximum size of a front matrix          =          653796
     maximum size of a front trapezoid       =          372171
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      7.7596D+09
     no. of floating point ops for solve     =      6.0466D+07
     ratio of flops for factor (min/max)     =          0.9396
     ratio of allocated memory (max/min)     =          1.1524
     number of positive pivots               =           53106
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.006000
     time (cpu & wall) for ordering          =        0.140625        0.132000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.062500        0.068000
     time (cpu & wall) for numeric factor    =        0.171875        0.178000
     computational rate (gflops) for factor  =       45.146769       43.593263
     time (cpu & wall) for numeric solve     =        0.015625        0.012000
     computational rate (gflops) for solve   =        3.869828        5.038839
     effective I/O rate (GB/sec) for solve   =       14.417378       18.772628

     no input or output performed

  Solver Memory allocated on core    0       =       55.745 MB
  Solver Memory allocated on core    1       =       52.541 MB
  Solver Memory allocated on core    2       =       60.550 MB
  Solver Memory allocated on core    3       =       55.653 MB
  Total Solver Memory allocated by all cores =      224.490 MB

