
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           53106
     no. of nonzeroes in lower triangle of a =         2390177
     no. of nonzeroes in the factor l        =        15997470
     ratio of nonzeroes in factor (min/max)  =          0.8570
     number of super nodes                   =            2013
     maximum order of a front matrix         =            1194
     maximum size of a front matrix          =          713415
     maximum size of a front trapezoid       =          632412
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      7.7941D+09
     no. of floating point ops for solve     =      6.0249D+07
     ratio of flops for factor (min/max)     =          0.8566
     ratio of allocated memory (max/min)     =          1.1780
     number of positive pivots               =           53106
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.041000
     time (cpu & wall) for ordering          =        0.140625        0.142000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.093750        0.095000
     time (cpu & wall) for numeric factor    =        0.234375        0.224000
     computational rate (gflops) for factor  =       33.254830       34.795092
     time (cpu & wall) for numeric solve     =        0.015625        0.013000
     computational rate (gflops) for solve   =        3.855924        4.634524
     effective I/O rate (GB/sec) for solve   =       14.365575       17.266317

     no input or output performed

  Solver Memory allocated on core    0       =       60.755 MB
  Solver Memory allocated on core    1       =       55.841 MB
  Solver Memory allocated on core    2       =       54.888 MB
  Solver Memory allocated on core    3       =       51.576 MB
  Total Solver Memory allocated by all cores =      223.059 MB

