
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           52738
     no. of nonzeroes in lower triangle of a =         2377131
     no. of nonzeroes in the factor l        =        16157664
     ratio of nonzeroes in factor (min/max)  =          0.8567
     number of super nodes                   =            1993
     maximum order of a front matrix         =            1128
     maximum size of a front matrix          =          636756
     maximum size of a front trapezoid       =          352875
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      7.9378D+09
     no. of floating point ops for solve     =      6.0899D+07
     ratio of flops for factor (min/max)     =          0.8996
     ratio of allocated memory (max/min)     =          1.1664
     number of positive pivots               =           52738
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.011000
     time (cpu & wall) for ordering          =        0.156250        0.157000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.078125        0.100000
     time (cpu & wall) for numeric factor    =        0.250000        0.244000
     computational rate (gflops) for factor  =       31.751325       32.532095
     time (cpu & wall) for numeric solve     =        0.015625        0.014000
     computational rate (gflops) for solve   =        3.897522        4.349913
     effective I/O rate (GB/sec) for solve   =       14.520554       16.205975

     no input or output performed

  Solver Memory allocated on core    0       =       54.754 MB
  Solver Memory allocated on core    1       =       52.319 MB
  Solver Memory allocated on core    2       =       61.027 MB
  Solver Memory allocated on core    3       =       55.535 MB
  Total Solver Memory allocated by all cores =      223.635 MB

