
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           53106
     no. of nonzeroes in lower triangle of a =         4406448
     no. of nonzeroes in the factor l        =        20446920
     ratio of nonzeroes in factor (min/max)  =          0.9245
     number of super nodes                   =            1678
     maximum order of a front matrix         =            1272
     maximum size of a front matrix          =          809628
     maximum size of a front trapezoid       =          441117
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.2523D+10
     no. of floating point ops for solve     =      7.8086D+07
     ratio of flops for factor (min/max)     =          0.8727
     ratio of allocated memory (max/min)     =          1.3370
     number of positive pivots               =           53106
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.015625        0.038377
     time (cpu & wall) for ordering          =        0.062500        0.056328
     time (cpu & wall) for other matrix prep =        0.000000        0.013140
     time (cpu & wall) for value input       =        0.015625        0.027765
     time (cpu & wall) for matrix distrib.   =        0.140625        0.140956
     time (cpu & wall) for numeric factor    =        0.312500        0.314107
     computational rate (gflops) for factor  =       40.072950       39.867984

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB         99142.        1. MB
                95-   1        131072.        1. MB        107035.        1. MB
                95-   2        131072.        1. MB        110739.        1. MB
                95-   3        131072.        1. MB        100692.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        417608.        3. MB


  Solver Memory allocated on core    0       =       87.773 MB
  Solver Memory allocated on core    1       =       80.665 MB
  Solver Memory allocated on core    2       =       95.686 MB
  Solver Memory allocated on core    3       =      107.849 MB
  Total Solver Memory allocated by all cores =      371.974 MB

